"""Obsidian vault writer — scaffold + per-artifact write plumbing.

This module owns every sanctioned write path into ``~/SecondBrain/cee/``
per bible 00 §11 ("Use a single ``obsidian_writer.py`` module; never
write to the vault directly from anywhere else") and bible 13 §11
("Writer location: ``~/cee/persistence/obsidian_writer.py``"). Phase 3
T4 renamed this file from ``persistence/obsidian.py`` to align with
bible 04 §5.1 + bible 20 §5.3 + bible 18's canonical naming, and
extended it with the :func:`write_artifact` plumbing layer.

Public surface:

* :func:`scaffold_obsidian` — Phase 1 vault layout scaffold (preserved
  verbatim from the pre-rename module).
* :func:`write_artifact` — Phase 3 T4 plumbing: resolves the canonical
  vault path for a given (kind, id) pair and atomically writes the
  caller-rendered content via :func:`persistence.filesystem_write_text`.
  The role is hard-coded to :attr:`RoleEnum.OBSIDIAN_WRITER` per the
  bible-canonical sole-writer constraint cited above; a ``role``
  parameter would invite footguns where a caller passes another role
  and gets a :class:`RoleSurfaceViolation`.

Closed artifact-kind enum (bible 13 Rule 5):

* ``run`` — per §5.2, lands at ``runs/<run_id>.md``
* ``skill`` — per §5.3, lands at ``skills/<slug>.md``
* ``agent`` — per §5.4, lands at ``agents/<slug>.md``
* ``bible_section`` — per §5.5, lands at ``bible/<NN>_<slug>.md``
* ``audit_summary`` — per §5.6, lands at ``audit/<YYYY-MM-DD>.md``

The sixth note type from bible 13 Rule 5 (``index``) is intentionally
excluded from :func:`write_artifact` — index notes are scaffold-time
creations regenerated by ``cee resync-obsidian`` (per Rule 9 + §EC),
not pipeline-time per-artifact writes.

**Idempotency.** Same (kind, id, content) input → same on-disk bytes,
since :func:`persistence.atomic.atomic_write_text` truncates +
replaces atomically. The strict bible 13 §5.10 hash-and-skip
optimization (read-existing → SHA → compare → skip on match) is
content-aware renderer-layer concern; deferred to Phase 5+ (see
``# TODO #36`` marker below).

# TODO #35 / bible 13 §11: Phase 5+ public API write_run / write_skill /
# write_agent / write_bible_section will wrap write_artifact() once the
# per-kind renderers ship under persistence/obsidian/renderers/.

# TODO #36 / bible 13 §5.10: hash-and-skip idempotency optimization
# deferred to Phase 5+ renderer layer; T4 ships filesystem-level atomic
# overwrite only.

──────────────────────────────────────────────────────────────────────
Original Phase 1 module docstring follows (preserved for context):
──────────────────────────────────────────────────────────────────────

Per bible 13 §5.1, the vault layout is:

.. code-block:: text

    ~/SecondBrain/cee/
    ├── README.md                       # frontmatter type=meta
    ├── runs/
    │   └── index.md                    # frontmatter type=index, indexes=run
    ├── skills/
    │   └── index.md                    # frontmatter type=index, indexes=skill
    ├── agents/
    │   └── index.md                    # frontmatter type=index, indexes=agent
    ├── bible/
    │   └── index.md                    # frontmatter type=index, indexes=bible
    ├── audit/
    │   └── index.md                    # frontmatter type=index, indexes=audit
    └── _templates/                     # intentionally empty in Phase 1

This module backs ``cee init`` and ``cee scaffold-obsidian`` (the boot-time
verbs invoked under bible 13 §EC1 and §10.10). It is **layout-only** — no
renderers, no per-Run note writers, no frontmatter builder, no wiki-link
helper. Those modules are deferred to Phase 5+ and will live at:

- ``~/cee/persistence/obsidian/renderers/{run,skill,agent,bible_section,audit_summary}.py``
- ``~/cee/persistence/obsidian/frontmatter.py``
- ``~/cee/persistence/obsidian/links.py``
- ``~/cee/persistence/obsidian/indexes.py``
- ``~/cee/persistence/obsidian/idempotent.py``  (strict §5.10 hash-and-skip)

Bible 13 §5.1 lists five template files inside ``_templates/`` (``run.md``,
``skill.md``, ``agent.md``, ``bible_section.md``, ``audit_summary.md``).
Phase 1 creates the directory empty; the template files are written by the
renderers when they ship in Phase 5+.

**Idempotency.** :func:`_idempotent_write` uses *create-only* semantics —
a pre-existing file is never modified, regardless of content. This is
*stricter* than the bible 13 §5.10 hash-and-skip rule (which governs the
per-Run writer): scaffold extends the spirit of §EC3 (manual-edit
preservation) to setup, since ``cee init`` may run after the OPERATOR has
customised README.md or an index file. The strict §5.10 hash-and-skip
will live in the deferred per-Run writer.

**Failure mode.** Filesystem errors propagate to the caller. Bible 02
§7.10 cross-references bible 00 Rule 9: Obsidian write failures are
non-fatal at the *pipeline* level — the caller (``cee init``,
``cee scaffold-obsidian``) decides whether to log-and-continue or surface.
This function does not swallow on its own.
"""

from __future__ import annotations

from pathlib import Path
from typing import Literal

import paths
from persistence.atomic import atomic_write_text
from persistence.filesystem_writer import write_text as _filesystem_write_text
from roles import RoleEnum

ObsidianArtifactKind = Literal[
    "run", "skill", "agent", "bible_section", "audit_summary"
]

# ─── Rendered content (bible 13 §5.1, §5.7) ─────────────────────────────

_README_CONTENT = """\
---
type: meta
---

# CEE Vault

This vault is CEE's human-readable mirror layer. Filesystem at `~/cee/` is canonical; this vault is derived. Edits here do not propagate back to filesystem. See bible 13 for details.
"""

_INDEX_BODY_NOTE = (
    "This index is regenerated by `cee resync-obsidian`. "
    "Run that command after Skills, agents, Runs, or bible content are added."
)


def _render_index(indexes: str, heading: str) -> str:
    """Render an index.md stub per bible 13 §5.7.

    Frontmatter contains only the bible-specified ``type`` and ``indexes``
    keys. The body is a heading plus a placeholder note pointing at
    ``cee resync-obsidian``. **No Dataview queries** — those come with
    the index renderer in Phase 5+.
    """
    return (
        "---\n"
        "type: index\n"
        f"indexes: {indexes}\n"
        "---\n"
        "\n"
        f"# {heading} Index\n"
        "\n"
        f"{_INDEX_BODY_NOTE}\n"
    )


def _idempotent_write(path: Path, content: str) -> bool:
    """Write ``content`` to ``path`` only if ``path`` does not exist.

    Returns ``True`` if a write occurred; ``False`` if the path was
    already present (and therefore preserved untouched).

    **Scaffold-specific semantics** (stricter than bible 13 §5.10).
    The §5.10 algorithm — hash the rendered content, skip on match,
    overwrite on mismatch — is the right rule for the per-Run note
    writer where canon must win over stale content. Scaffold is invoked
    by ``cee init`` and ``cee scaffold-obsidian`` (bible 13 §EC1, §10.10),
    which are *setup* verbs; the OPERATOR may already have customised
    the vault. Scaffold therefore extends the spirit of bible 13 §EC3
    (manual-edit preservation) to initialisation: existing files are
    OPERATOR property and are never modified by setup.

    The strict §5.10 hash-and-skip lives in the deferred per-Run writer
    at ``~/cee/persistence/obsidian/idempotent.py`` (Phase 5+).

    Byte equality, not SHA-256: scaffold files are tiny (one README plus
    five tiny index stubs). The §5.10 hash optimisation matters when
    notes are many KB; here a missing-file check suffices.
    """
    if path.exists():
        return False
    atomic_write_text(path, content)
    return True


def scaffold_obsidian() -> dict[str, int]:
    """Create the Obsidian vault directory structure at ``OBSIDIAN_VAULT``.

    Per bible 13 §5.1, this materialises the seven directories
    (vault root + ``runs/``, ``skills/``, ``agents/``, ``bible/``,
    ``audit/``, ``_templates/``), the root ``README.md``, and an
    ``index.md`` stub in each of the five content subdirectories
    (``runs/``, ``skills/``, ``agents/``, ``bible/``, ``audit/`` —
    ``_templates/`` is left empty in Phase 1).

    Returns
    -------
    dict
        ``{"directories_created": int, "files_created": int}`` — counts
        only items that did not already exist. Fresh install:
        ``{"directories_created": 7, "files_created": 6}``. Re-run on a
        scaffolded vault: ``{"directories_created": 0, "files_created": 0}``.

    Raises
    ------
    OSError
        Filesystem errors (permission denied, disk full, ...) propagate
        unswallowed. Per bible 02 §7.10 → bible 00 Rule 9, Obsidian
        failures are non-fatal at the *pipeline* level — the caller
        decides whether to log-and-continue or surface.

    Notes
    -----
    The ``_templates/`` directory is intentionally empty in Phase 1.
    Bible 13 §5.1 lists five template files inside it (one per renderer)
    that will be written when their renderers ship in Phase 5+.

    Idempotency uses *create-only* semantics via :func:`_idempotent_write`,
    which is stricter than bible 13 §5.10's hash-and-skip rule used by
    the per-Run writer.
    """
    scaffold_dirs: tuple[Path, ...] = (
        paths.OBSIDIAN_VAULT,
        paths.OBSIDIAN_RUNS_DIR,
        paths.OBSIDIAN_SKILLS_DIR,
        paths.OBSIDIAN_AGENTS_DIR,
        paths.OBSIDIAN_BIBLE_DIR,
        paths.OBSIDIAN_AUDIT_DIR,
        paths.OBSIDIAN_TEMPLATES_DIR,
    )

    # Each tuple: (content_dir, indexes value per §5.7, heading word).
    index_specs: tuple[tuple[Path, str, str], ...] = (
        (paths.OBSIDIAN_RUNS_DIR, "run", "Runs"),
        (paths.OBSIDIAN_SKILLS_DIR, "skill", "Skills"),
        (paths.OBSIDIAN_AGENTS_DIR, "agent", "Agents"),
        (paths.OBSIDIAN_BIBLE_DIR, "bible", "Bible"),
        (paths.OBSIDIAN_AUDIT_DIR, "audit", "Audit"),
    )

    directories_created = 0
    for directory in scaffold_dirs:
        if not directory.exists():
            directories_created += 1
        paths.ensure_dir(directory)

    files_created = 0
    if _idempotent_write(paths.OBSIDIAN_VAULT / "README.md", _README_CONTENT):
        files_created += 1

    for content_dir, indexes_value, heading in index_specs:
        rendered = _render_index(indexes_value, heading)
        if _idempotent_write(content_dir / "index.md", rendered):
            files_created += 1

    return {
        "directories_created": directories_created,
        "files_created": files_created,
    }


# ─── Phase 3 T4: write_artifact plumbing ────────────────────────────────


def _kind_dirs() -> dict[str, Path]:
    """Build the per-kind vault directory map from current ``paths.*``.

    Built per-call (not at module import) so tests that monkey-patch
    ``paths.OBSIDIAN_*`` get the override propagated. Mirrors
    :func:`persistence.filesystem_writer._rebuild_allowed_writes`.
    """
    return {
        "run":           paths.OBSIDIAN_RUNS_DIR,
        "skill":         paths.OBSIDIAN_SKILLS_DIR,
        "agent":         paths.OBSIDIAN_AGENTS_DIR,
        "bible_section": paths.OBSIDIAN_BIBLE_DIR,
        "audit_summary": paths.OBSIDIAN_AUDIT_DIR,
    }


def _resolve_vault_path(kind: ObsidianArtifactKind, artifact_id: str) -> Path:
    """Resolve the canonical vault target for ``(kind, artifact_id)``.

    Per bible 13 §5.2–§5.6 each artifact kind lives in its own
    subdirectory under :data:`paths.OBSIDIAN_VAULT` with filename
    ``<artifact_id>.md``. ``KeyError`` is raised when ``kind`` is not
    one of the five canonical members of :data:`ObsidianArtifactKind`
    (the ``index`` note type is intentionally not a write target).
    """
    return _kind_dirs()[kind] / f"{artifact_id}.md"


def write_artifact(
    artifact_kind: ObsidianArtifactKind,
    artifact_id: str,
    content: str,
    *,
    run_id: str | None = None,
) -> Path:
    """Atomically write an artifact note to the Obsidian vault.

    Resolves the canonical vault path for ``(artifact_kind,
    artifact_id)`` per bible 13 §5.1's layout, then delegates to
    :func:`persistence.filesystem_write_text` with the role hard-coded
    to :attr:`RoleEnum.OBSIDIAN_WRITER`. The caller renders ``content``
    (Markdown body + frontmatter); T4 is plumbing only — Markdown
    rendering is renderer-layer (Phase 5+) per the module docstring.

    Parameters
    ----------
    artifact_kind
        One of the five canonical kinds in :data:`ObsidianArtifactKind`.
    artifact_id
        The unique identifier within the kind's subdirectory (e.g.,
        ``run_id`` for runs, ``slug`` for skills/agents, ``<NN>_<slug>``
        for bible sections, ``<YYYY-MM-DD>`` for audit summaries).
    content
        Already-rendered Markdown (frontmatter + body). T4 writes
        bytes verbatim; renderers are Phase 5+ work.
    run_id
        Run identifier for forensic correlation if a denial audit
        emission fires (see :func:`persistence.filesystem_write_text`).

    Returns
    -------
    Path
        The resolved+written target path.

    Raises
    ------
    KeyError
        If ``artifact_kind`` is not a canonical member.
    RoleSurfaceViolation
        Structurally unreachable — :func:`_resolve_vault_path` always
        produces a path under :data:`paths.OBSIDIAN_VAULT`, which is
        :attr:`RoleEnum.OBSIDIAN_WRITER`'s allowed root per bible 02
        §7.10. Any raise here would indicate a paths.py corruption.
    """
    target = _resolve_vault_path(artifact_kind, artifact_id)
    _filesystem_write_text(
        RoleEnum.OBSIDIAN_WRITER, target, content, run_id=run_id
    )
    return target
